function publicBookingServices() {
  const sheet = SpreadsheetApp.getActive().getSheetByName("SERVICES");
  if (!sheet || sheet.getLastRow() < 2) return [];
  const width = typeof sheet.getLastColumn === "function" ? Math.max(6, sheet.getLastColumn()) : 6;
  const headers = width > 6
    ? sheet.getRange(1, 1, 1, width).getValues()[0].map((value) =>
      String(value || "").trim().toUpperCase().replace(/[\s-]+/g, "_"))
    : [];
  const preparationIndex = headers.indexOf("PREPARATION_MINUTES");
  const cleanupIndex = headers.indexOf("CLEANUP_MINUTES");
  const rows = sheet.getRange(2, 1, sheet.getLastRow() - 1, width).getValues();
  return rows.map((row, index) => {
    const rawDuration = String(row[5] == null ? "" : row[5]).trim();
    return {
      name: String(row[0] || "").trim(),
      price: parseSheetAmount(row[1]),
      active: parseServiceActiveFlag(row[2]),
      order: Number(row[3]) || index + 1,
      // Missing legacy IDs are reported, never generated by this read action.
      serviceId: String(row[4] || "").trim(),
      durationMinutes: rawDuration ? Number(row[5]) : 30,
      preparationMinutes: preparationIndex >= 0 ? Math.max(0, Number(row[preparationIndex]) || 0) : 0,
      cleanupMinutes: cleanupIndex >= 0 ? Math.max(0, Number(row[cleanupIndex]) || 0) : 0
    };
  }).filter((service) => {
    const name = service.name.toLowerCase();
    const separators = (name.match(/[-–—]/g) || []).length;
    const isPackage = /[+＋]/.test(name)
      || /باك(?:ي)?دج|package|pack|vip/i.test(name)
      || separators >= 2;
    return service.name && service.serviceId && service.active && !isPackage;
  }).sort((a, b) => a.order - b.order);
}

function getPublicBookingServiceIds(data) {
  const values = data && Array.isArray(data.serviceIds)
    ? data.serviceIds
    : String((data && data.serviceId) || "").split(",");
  return values.map((value) => String(value || "").trim()).filter(Boolean);
}

function bookingServiceIdsInputIsValid(data) {
  return !data || !Object.prototype.hasOwnProperty.call(data, "serviceIds") ||
    Array.isArray(data.serviceIds);
}

function bookingServiceIdsHaveDuplicates(serviceIds) {
  const ids = Array.isArray(serviceIds) ? serviceIds : [];
  return new Set(ids).size !== ids.length;
}

function getSelectedPublicBookingServices(data, services) {
  const ids = getPublicBookingServiceIds(data);
  const selected = services.filter((service) => ids.indexOf(service.serviceId) !== -1);
  return selected.length ? selected : services.slice(0, 1);
}

function applyBookingOccupancySnapshot(booking, preparationMinutes, cleanupMinutes, configurationVersion, occupiedTime) {
  const start = bookingMinutes(occupiedTime || booking.time);
  const duration = Math.max(15, Number(booking.durationMinutes) || 30);
  const preparation = Math.max(0, Number(preparationMinutes) || 0);
  const cleanup = Math.max(0, Number(cleanupMinutes) || 0);
  booking.serviceDurationSnapshot = duration;
  booking.preparationMinutesSnapshot = preparation;
  booking.cleanupMinutesSnapshot = cleanup;
  booking.occupiedStartTime = start === null ? "" : minutesToBookingTime(start - preparation);
  booking.occupiedEndTime = start === null ? "" : minutesToBookingTime(start + duration + cleanup);
  booking.serviceConfigurationVersion = String(configurationVersion || "").trim();
  return booking;
}

function commitBookingPhase5UnderCurrentLock(options) {
  const data = options.data || {};
  const booking = options.booking;
  const fallbackHash = typeof BookingAvailabilityPhase5 !== "undefined"
    ? BookingAvailabilityPhase5.hash({
      action: options.action, bookingId: booking.id, updatedAt: booking.updatedAt,
      status: booking.status, date: booking.date, time: booking.time
    })
    : String(booking.id || "").replace(/[^A-Za-z0-9]/g, "").slice(-24);
  const requestId = String(options.requestId || data.clientRequestId ||
    `BOOKING-${fallbackHash}`).trim();
  if (typeof bookingAvailabilityPhase5RunTransaction !== "function" ||
      bookingAvailabilityEngineMode() === "LEGACY") {
    options.business();
    if (typeof bookingAvailabilityPhase5AfterBookingMutationUnderLock === "function") {
      bookingAvailabilityPhase5AfterBookingMutationUnderLock(data, booking);
    }
    return booking;
  }
  const actor = typeof bookingAvailabilityPhase5Actor === "function"
    ? bookingAvailabilityPhase5Actor(data, true) : null;
  return bookingAvailabilityPhase5RunTransaction({
    data,
    requestId,
    action: options.action,
    entityType: "BOOKING",
    entityId: booking.id,
    branchId: booking.branchId,
    date: booking.date,
    actor,
    beforeState: options.beforeState || {},
    business: () => {
      options.business();
      return booking;
    },
    version: () => bookingAvailabilityPhase5IncrementVersion(
      "booking", booking.branchId, booking.date, actor),
    audit: () => bookingAvailabilityPhase5AppendAudit({
      action: options.action,
      entityType: "BOOKING",
      entityId: booking.id,
      branchId: booking.branchId,
      staffId: booking.employeeId,
      date: booking.date,
      actorId: actor ? actor.actorId : "public",
      actorRole: actor ? actor.role : "PUBLIC",
      reasonCode: options.reasonCode || options.action,
      beforeState: options.beforeState || {},
      afterState: {
        status: booking.status, date: booking.date, time: booking.time,
        staffId: booking.employeeId,
        serviceConfigurationVersion: booking.serviceConfigurationVersion
      },
      requestId
    }),
    compensateBusiness: () => options.compensate()
  });
}

function committedBookingMutationRetry(data) {
  if (typeof bookingAvailabilityPhase5CommittedResultForRequest !== "function" ||
      bookingAvailabilityEngineMode() !== "PHASE5") return null;
  const requestId = String((data && data.clientRequestId) || "").trim();
  return bookingAvailabilityPhase5CommittedResultForRequest(requestId);
}

function bookingServiceSetHash(services, fallbackIds) {
  const configuration = (services || []).map((service) => ({
    serviceId: String(service.serviceId || "").trim(),
    durationMinutes: Number(service.durationMinutes) || 0,
    preparationMinutes: Number(service.preparationMinutes) || 0,
    cleanupMinutes: Number(service.cleanupMinutes) || 0
  })).sort((left, right) => left.serviceId.localeCompare(right.serviceId));
  const value = configuration.length ? configuration :
    (fallbackIds || []).map((serviceId) => ({ serviceId: String(serviceId || "").trim() }));
  return typeof BookingAvailabilityPhase5 !== "undefined"
    ? BookingAvailabilityPhase5.hash(value) : JSON.stringify(value);
}

function resolveTrustedBookingServiceTotals(booking, services) {
  const ids = Array.isArray(booking.serviceIds) ? booking.serviceIds : [];
  if (!ids.length) {
    if (!booking.service || !isValidBookingDuration(booking.durationMinutes) ||
        !isValidBookingPrice(booking.totalPrice)) {
      return bookingAppointmentValidationError("INVALID_SERVICES", "The booking service configuration is invalid.");
    }
    return {
      ok: true,
      durationMinutes: Number(booking.durationMinutes),
      totalPrice: Number(booking.totalPrice) || 0,
      preparationMinutes: Number(booking.preparationMinutes) || 0,
      cleanupMinutes: Number(booking.cleanupMinutes) || 0,
      serviceSetHash: bookingServiceSetHash([], booking.serviceIds || [])
    };
  }
  if (bookingServiceIdsHaveDuplicates(ids)) {
    return bookingAppointmentValidationError("INVALID_SERVICES", "Duplicate service IDs are not allowed.");
  }
  const available = Array.isArray(services) ? services : publicBookingServices();
  const selected = available.filter((service) => ids.indexOf(service.serviceId) !== -1);
  if (selected.length !== ids.length || !selected.length ||
      !selected.every((service) =>
        isValidBookingDuration(service.durationMinutes) && isValidBookingPrice(service.price))) {
    return bookingAppointmentValidationError("INVALID_SERVICES", "One or more booking services are unavailable.");
  }
  const durationMinutes = selected.reduce((sum, service) => sum + Number(service.durationMinutes), 0);
  const totalPrice = selected.reduce((sum, service) => sum + Number(service.price), 0);
  const preparationMinutes = selected.reduce((sum, service) =>
    sum + Math.max(0, Number(service.preparationMinutes) || 0), 0);
  const cleanupMinutes = selected.reduce((sum, service) =>
    sum + Math.max(0, Number(service.cleanupMinutes) || 0), 0);
  if (!isValidBookingDuration(durationMinutes) || !isValidBookingPrice(totalPrice)) {
    return bookingAppointmentValidationError("INVALID_SERVICES", "The booking service configuration is invalid.");
  }
  return {
    ok: true, durationMinutes, totalPrice, preparationMinutes, cleanupMinutes,
    serviceSetHash: bookingServiceSetHash(selected, ids)
  };
}

