(function (root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.StaffAttendanceSchema = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const SCHEMA_VERSION = "STAFF_ATTENDANCE_V4";

  const SHEET_SCHEMAS = Object.freeze({
    BARBER_SCHEDULE: Object.freeze([
      "SCHEDULE_ID", "STAFF_ID", "STAFF_NAME", "WEEKDAY", "SHIFT_START",
      "SHIFT_END", "ACTIVE", "UPDATED_AT", "SEGMENT_INDEX",
      "REQUIRED_WORK_MINUTES", "ALLOWED_BREAK_MINUTES", "EFFECTIVE_FROM",
      "EFFECTIVE_TO", "CREATED_AT", "CREATED_BY", "UPDATED_BY", "BRANCH_ID",
      "LAST_REQUEST_ID", "RECORD_TYPE"
    ]),
    STAFF_SCHEDULE_OVERRIDES: Object.freeze([
      "OVERRIDE_ID", "STAFF_ID", "STAFF_NAME", "DATE", "TYPE", "SEGMENT_INDEX",
      "SHIFT_START", "SHIFT_END", "REQUIRED_WORK_MINUTES", "ALLOWED_BREAK_MINUTES",
      "BLOCK_START", "BLOCK_END", "REASON", "STATUS", "APPROVED_BY",
      "APPROVED_AT", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY",
      "SCOPE_TYPE", "BRANCH_ID", "SOURCE_EVIDENCE", "REQUESTED_BY",
      "REVIEW_REASON", "CANCELLED_AT", "CANCELLED_BY",
      "CANCELLATION_REASON", "LAST_REQUEST_ID", "EFFECT_SCOPE"
    ]),
    ATTENDANCE: Object.freeze([
      "ID", "DATE", "STAFF_ID", "STAFF_NAME", "RECORD_TYPE", "SHIFT_START",
      "CHECK_IN", "BREAK_OUT", "BREAK_IN", "CHECK_OUT", "WORK_HOURS",
      "BREAK_HOURS", "LATE_HOURS", "SHORT_HOURS", "ABSENCE_DAYS",
      "PENALTY_AMOUNT", "PENALTY_REASON", "SUGGESTED_DEDUCTION",
      "APPROVED_DEDUCTION", "APPROVAL_STATUS", "APPROVED_BY", "NOTE",
      "CREATED_AT", "UPDATED_AT",
      "ATTENDANCE_DAY_ID", "BRANCH_ID", "ATTENDANCE_DATE", "TIMEZONE",
      "STATUS", "SCHEDULE_SOURCE", "SCHEDULE_SOURCE_IDS", "SCHEDULED_START",
      "SCHEDULED_END", "SHIFT_SEGMENTS", "REQUIRED_WORK_MINUTES_RAW",
      "REQUIRED_WORK_MINUTES_ROUNDED", "ALLOWED_BREAK_MINUTES",
      "ACTUAL_CHECK_IN", "ACTUAL_CHECK_OUT", "SESSION_COUNT",
      "PRESENCE_MINUTES_RAW", "PRESENCE_MINUTES_ROUNDED",
      "ACTUAL_BREAK_MINUTES_RAW", "ACTUAL_BREAK_MINUTES_ROUNDED",
      "PAID_BREAK_CREDIT_MINUTES_RAW", "WORKED_MINUTES_RAW",
      "WORKED_MINUTES_ROUNDED", "CREDITED_WORK_MINUTES_RAW",
      "LATE_MINUTES_RAW", "LATE_MINUTES_ROUNDED",
      "EARLY_LEAVE_MINUTES_RAW", "EARLY_LEAVE_MINUTES_ROUNDED",
      "EXCESS_BREAK_MINUTES_RAW", "EXCESS_BREAK_MINUTES_ROUNDED",
      "DEFICIT_MINUTES_RAW", "DEFICIT_MINUTES_ROUNDED",
      "RAW_OVERTIME_MINUTES", "ELIGIBLE_OVERTIME_MINUTES",
      "APPROVED_OVERTIME_MINUTES",
      "OVERTIME_APPROVAL_STATUS", "LEAVE_OR_ABSENCE_TYPE", "OPEN_SESSION",
      "OPEN_BREAK", "CALCULATION_WARNINGS", "POLICY_ID", "POLICY_SNAPSHOT",
      "SCHEDULE_SNAPSHOT", "SOURCE_EVENT_IDS", "SOURCE_EVENT_HASH",
      "STALE_CALCULATION", "LAST_EVENT_AT", "CALCULATED_AT", "DAY_LIFECYCLE",
      "CALCULATION_VERSION", "LOCKED", "REOPENED_COUNT", "REOPENED_AT",
      "REOPENED_BY", "LAST_ACTION_ID", "LAST_REQUEST_ID"
    ]),
    ATTENDANCE_EVENTS: Object.freeze([
      "EVENT_ID", "ATTENDANCE_DAY_ID", "STAFF_ID", "STAFF_NAME", "DATE",
      "BRANCH_ID", "TIMEZONE", "EVENT_TYPE", "EVENT_AT", "SESSION_INDEX",
      "BREAK_INDEX", "EVENT_SEQUENCE", "STATUS",
      "REVERSES_EVENT_ID", "SOURCE_ENTITY_TYPE", "SOURCE_ENTITY_ID", "REASON",
      "CORRECTION_PAYLOAD_JSON", "ACTOR_ID", "ACTOR_NAME", "ACTOR_ROLE",
      "CREATED_AT", "REQUEST_ID", "REQUEST_FINGERPRINT"
    ]),
    STAFF_WORK_POLICIES: Object.freeze([
      "POLICY_ID", "STAFF_ID", "EFFECTIVE_FROM", "EFFECTIVE_TO",
      "REQUIRED_DAILY_MINUTES", "DEFAULT_SHIFT_START", "DEFAULT_SHIFT_END",
      "ALLOWED_BREAK_MINUTES", "BREAK_PAYMENT_TYPE", "ALLOW_MULTIPLE_BREAKS",
      "MAX_SINGLE_BREAK_MINUTES", "BREAK_GRACE_MINUTES",
      "EXCESS_BREAK_CONTRIBUTES_TO_DEFICIT", "GRACE_LATE_MINUTES",
      "GRACE_EARLY_LEAVE_MINUTES", "DEFICIT_RATE_TYPE",
      "DEFICIT_RATE_PER_HOUR", "FIXED_LATE_PENALTY", "DAILY_DEDUCTION_CAP",
      "OVERTIME_RATE_PER_HOUR", "OVERTIME_MULTIPLIER", "OVERTIME_POLICY",
      "OVERTIME_APPROVAL_REQUIRED", "MIN_OVERTIME_THRESHOLD_MINUTES",
      "DAILY_OVERTIME_CAP_MINUTES", "PERIOD_OVERTIME_CAP_MINUTES",
      "OVERTIME_ALLOWED_WINDOWS_JSON", "ROUNDING_INCREMENT_MINUTES",
      "ROUNDING_MODE", "SETTLEMENT_PERIOD", "MONTHLY_ALLOWED_LEAVE_DAYS",
      "LEAVE_CARRY_FORWARD", "MAX_CARRY_FORWARD_DAYS",
      "LEAVE_TYPES_CONSUMING_JSON", "LEAVE_TYPES_EXEMPT_JSON",
      "PARTIAL_LEAVE_UNIT", "LEAVE_APPROVAL_REQUIRED",
      "LEAVE_RESET_PERIOD", "HIRE_DATE_PRORATION", "TERMINATION_DATE_PRORATION",
      "EXCESS_ABSENCE_POLICY", "EXCESS_ABSENCE_MULTIPLIER",
      "EXCESS_ABSENCE_FIXED_AMOUNT", "MAX_EXCESS_ABSENCE_DEDUCTION",
      "DAY_VALUE_METHOD", "FIXED_DAY_VALUE", "MONTHLY_SALARY",
      "WORKING_DAYS_DIVISOR", "HOURLY_RATE", "CURRENCY", "ACTIVE", "CREATED_AT",
      "CREATED_BY", "UPDATED_AT", "UPDATED_BY",
      "CURRENCY_MINOR_SCALE", "SALARY_BASIS",
      "MONTHLY_SALARY_MINOR",
      "DEFICIT_RATE_MINOR_PER_MINUTE", "DAILY_DEDUCTION_CAP_MINOR",
      "PERIOD_DEDUCTION_CAP_MINOR", "OVERTIME_RATE_TYPE",
      "OVERTIME_RATE_MINOR_PER_MINUTE", "OVERTIME_MULTIPLIER_BPS",
      "UNPAID_LEAVE_MULTIPLIER_BPS", "ABSENCE_MULTIPLIER_BPS",
      "SICK_LEAVE_PAID", "UNRESOLVED_BEHAVIOR"
    ]),
    ATTENDANCE_ADJUSTMENTS: Object.freeze([
      "ADJUSTMENT_ID", "ATTENDANCE_DAY_ID", "STAFF_ID", "DATE", "TYPE",
      "BEFORE_STATE_JSON", "PROPOSED_STATE_JSON", "FINAL_STATE_JSON", "REASON",
      "STATUS", "REQUESTED_AT", "REQUESTED_BY", "REVIEWED_AT", "REVIEWED_BY",
      "REVIEW_NOTE", "APPLIED_AT", "APPLIED_BY", "ACTION_ID", "REQUEST_ID",
      "REQUEST_FINGERPRINT"
    ]),
    STAFF_LEAVE_LEDGER: Object.freeze([
      "LEAVE_ENTRY_ID", "STAFF_ID", "STAFF_NAME", "PERIOD_KEY", "DATE",
      "LEAVE_TYPE", "SOURCE_OVERRIDE_ID", "UNITS_DAYS", "MINUTES", "DIRECTION",
      "STATUS", "REVERSES_ENTRY_ID", "SETTLEMENT_ID", "POLICY_ID",
      "POLICY_SNAPSHOT_JSON", "REASON", "CREATED_AT", "CREATED_BY", "REQUEST_ID"
    ]),
    ATTENDANCE_OVERTIME_APPROVALS: Object.freeze([
      "OVERTIME_APPROVAL_ID", "ATTENDANCE_DAY_ID", "STAFF_ID", "DATE",
      "RAW_OVERTIME_MINUTES", "APPROVED_OVERTIME_MINUTES", "STATUS",
      "DECISION_REASON", "DECIDED_AT", "DECIDED_BY", "REVERSES_APPROVAL_ID",
      "DAY_CALCULATION_VERSION", "DAY_LAST_EVENT_AT", "DAY_SOURCE_EVENT_HASH",
      "STALE", "CREATED_AT",
      "CREATED_BY", "REQUEST_ID", "REQUEST_FINGERPRINT"
    ]),
    PAYROLL_ATTENDANCE_PERIODS: Object.freeze([
      "PAYROLL_PERIOD_ID", "SCOPE_TYPE", "BRANCH_ID", "START_DATE", "END_DATE",
      "TIMEZONE", "STATUS", "CALCULATION_VERSION", "SOURCE_EMPLOYEE_HASH",
      "NOTES", "CREATED_BY", "CREATED_AT", "CALCULATED_BY", "CALCULATED_AT",
      "SUBMITTED_BY", "SUBMITTED_AT", "APPROVED_BY", "APPROVED_AT",
      "LOCKED_BY", "LOCKED_AT", "REOPENED_BY", "REOPENED_AT",
      "REOPEN_REASON", "UPDATED_BY", "UPDATED_AT", "LAST_REQUEST_ID"
    ]),
    PAYROLL_ATTENDANCE_SETTLEMENTS: Object.freeze([
      "SETTLEMENT_ID", "STAFF_ID", "STAFF_NAME", "PERIOD_START", "PERIOD_END",
      "SETTLEMENT_PERIOD", "REQUIRED_MINUTES", "WORKED_MINUTES",
      "DEFICIT_MINUTES", "RAW_OVERTIME_MINUTES", "APPROVED_OVERTIME_MINUTES",
      "ALLOWED_LEAVE_DAYS", "CONSUMED_LEAVE_DAYS", "EXCESS_ABSENCE_DAYS",
      "DEFICIT_VALUE", "OVERTIME_VALUE", "EXCESS_ABSENCE_DEDUCTION",
      "MANUAL_ADJUSTMENTS", "NET_ATTENDANCE_ADJUSTMENT", "DAY_VALUE",
      "DAY_VALUE_METHOD", "POLICY_ID", "POLICY_SNAPSHOT_JSON",
      "CALCULATION_VERSION", "STATUS", "APPROVED_BY", "APPROVED_AT", "LOCKED",
      "LOCKED_AT", "LOCKED_BY", "REOPENED_AT", "REOPENED_BY",
      "REOPEN_REASON", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY",
      "LAST_REQUEST_ID", "CURRENCY", "DEFICIT_VALUE_MINOR", "OVERTIME_VALUE_MINOR",
      "EXCESS_ABSENCE_DEDUCTION_MINOR", "MANUAL_ADJUSTMENTS_MINOR",
      "NET_ATTENDANCE_ADJUSTMENT_MINOR",
      "PAYROLL_PERIOD_ID", "SETTLEMENT_VERSION", "STAFF_NAME_SNAPSHOT",
      "BRANCH_ID", "SALARY_BASIS", "BASE_SALARY_MINOR",
      "CONTRACTUAL_MINUTES", "ATTENDED_REQUIRED_MINUTES",
      "APPROVED_PAID_LEAVE_MINUTES", "UNPAID_LEAVE_MINUTES",
      "ABSENCE_MINUTES", "DEFICIT_RATE_MINOR_PER_MINUTE",
      "OVERTIME_RATE_MINOR_PER_MINUTE", "BASE_PERIOD_AMOUNT_MINOR",
      "DEFICIT_DEDUCTION_MINOR", "UNPAID_LEAVE_DEDUCTION_MINOR",
      "ABSENCE_DEDUCTION_MINOR", "OVERTIME_COMPENSATION_MINOR",
      "GROSS_ATTENDANCE_ADJUSTMENT_MINOR", "SOURCE_ATTENDANCE_DAY_IDS_JSON",
      "SOURCE_ATTENDANCE_SNAPSHOT_JSON", "SOURCE_AGGREGATE_HASH",
      "SALARY_SNAPSHOT_JSON", "WARNINGS_JSON", "STALE", "SUPERSEDES_SETTLEMENT_ID"
    ]),
    PAYROLL_ATTENDANCE_ADJUSTMENTS: Object.freeze([
      "ADJUSTMENT_ID", "SETTLEMENT_ID", "PAYROLL_PERIOD_ID", "STAFF_ID",
      "AMOUNT_MINOR", "DIRECTION", "CATEGORY", "REASON", "STATUS",
      "REQUESTED_BY", "REQUESTED_AT", "DECIDED_BY", "DECIDED_AT",
      "DECISION_REASON", "BEFORE_STATE_JSON", "AFTER_STATE_JSON",
      "REVERSES_ADJUSTMENT_ID", "REQUEST_ID", "REQUEST_FINGERPRINT"
    ]),
    PAYROLL_ATTENDANCE_AUDIT: Object.freeze([
      "ACTION_ID", "ENTITY_TYPE", "ENTITY_ID", "ACTION", "ACTOR_ID",
      "ACTOR_NAME", "ACTOR_ROLE", "STAFF_ID", "BRANCH_ID",
      "BEFORE_STATE_JSON", "AFTER_STATE_JSON", "REASON", "TIMESTAMP",
      "REQUEST_ID"
    ]),
    PAYROLL_ATTENDANCE_IDEMPOTENCY: Object.freeze([
      "REQUEST_ID", "ACTION", "ACTOR_ID", "REQUEST_FINGERPRINT",
      "RESPONSE_JSON", "STATUS", "CREATED_AT", "EXPIRES_AT"
    ]),
    STAFF_ATTENDANCE_AUDIT: Object.freeze([
      "ACTION_ID", "ENTITY_TYPE", "ENTITY_ID", "ACTION", "ACTOR_ID",
      "ACTOR_NAME", "ACTOR_ROLE", "STAFF_ID", "BEFORE_STATE_JSON",
      "AFTER_STATE_JSON", "REASON", "TIMESTAMP", "REQUEST_ID"
    ]),
    STAFF_ATTENDANCE_IDEMPOTENCY: Object.freeze([
      "REQUEST_ID", "ACTION", "ACTOR_ID", "REQUEST_FINGERPRINT",
      "RESPONSE_JSON", "STATUS", "CREATED_AT", "EXPIRES_AT"
    ])
  });

  const LEGACY_ATTENDANCE_HEADERS = Object.freeze(SHEET_SCHEMAS.ATTENDANCE.slice(0, 24));
  const LEGACY_SCHEDULE_HEADERS = Object.freeze([
    "SCHEDULE_ID", "STAFF_ID", "STAFF_NAME", "WEEKDAY",
    "SHIFT_START", "SHIFT_END", "ACTIVE", "UPDATED_AT"
  ]);

  const PERMISSIONS = Object.freeze([
    "attendance.view", "attendance.self_action", "attendance.manage",
    "attendance.correct", "attendance.approve_adjustment", "attendance.approve_overtime",
    "schedule.view", "schedule.manage", "leave.request", "leave.approve", "payroll_policy.view",
    "payroll_policy.manage", "payroll_settlement.view",
    "payroll_settlement.approve",
    "payroll_attendance.view", "payroll_attendance.calculate",
    "payroll_attendance.review", "payroll_attendance.approve",
    "payroll_attendance.lock", "payroll_attendance.reopen",
    "payroll_attendance.adjust", "payroll_attendance.export"
  ]);

  return Object.freeze({
    SCHEMA_VERSION,
    SHEET_SCHEMAS,
    LEGACY_ATTENDANCE_HEADERS,
    LEGACY_SCHEDULE_HEADERS,
    PERMISSIONS
  });
});
